
services:

  user_db:
    image: mysql:8.4
    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: project-api-rest
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest"]
      timeout: 20s
      retries: 15
      interval: 5s

    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos    

volumes:
  mysql_data:


