
services:

  vault:
    image: hashicorp/vault:latest
    container_name: vault-dev
    ports:
      - "8200:8200"
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - ./vault.hcl:/vault/config/vault.hcl
    networks:
      - vaultnet
    command: vault server -config=/vault/config/vault.hcl

  user_db:
    image: mysql:8.4
    ports:
      - "3307:3306"

    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: project-api-rest
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ptest"]
      timeout: 20s
      retries: 15
      interval: 5s

    networks:
      - vaultnet

    volumes:
      - mysql_data:/var/lib/mysql  # Persistencia de datos    

volumes:
  mysql_data:
  vault_data:
    external: true
    name: vault_vault_data



networks:
  vaultnet:
    external: true

