spring:
  application:
    name: api.rest

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  #baseline-on-migrate: true evita errores si la base ya tiene datos o tablas preexistentes.

  ai:
    openai:
      chat:
        base-url: https://generativelanguage.googleapis.com
        completions-path: /v1beta/openai/chat/completions
        options:
          model: gemini-2.0-flash
      api-key: ${SPRING_AI_OPENAI_API_KEY}

logging:
  level:
    org.springframework.cloud.vault: TRACE
    org.springframework.security: TRACE
    org:
      springframework:
        security: TRACE
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"



rsa:
  private-key: ${RSA_PRIVATE_KEY}
  public-key: ${RSA_PUBLIC_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html
    operationsSorter: method

